### ISSUE TITLE
Additional Methods

### ISSUE THREAD

**Issue by seanstar12** [jrjohnson/ember-cryptojs-shim#1]
I'm in the process of creating an AWS signing service for requests to ElasticSearch. This requires 'HmacSHA256'. How do you feel about adding additional modules to this shim? Do you have a preferred method besides just putting 
`generateModule('cryptojs/hmac-sha256', { 'default': CryptoJS.HmacSHA256 });`
into vendor/crypto.js?

**Comment by jrjohnson** [comment]
Adding new stuff would be great and I'm happy to merge it.  

The steps are 
1) add the `generateModeul` lint to crypto.js 
2) add it to the list in index.js on line 11 to get it exported into the containing app. 
3) Create a unit test which can pretty much be copied from any of the existing tests.
