### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by selvaa89** [jrjohnson/ember-cryptojs-shim#37]
Is it possible to include an option to import only the modules I need, instead of importing all the modules available?

This will help to reduce the size of vendor.js file.

**Comment by jrjohnson** [comment]
Thanks for the request. I've wanted to do this for quite some time. I will keep trying to find the time, but a PR would be welcome as well!

**Comment by jrjohnson** [comment]
Closing as this addon is now deprecated in favor of https://github.com/jrjohnson/ember-cryptojs-shim#deprecated-ember-cryptojs-shim
